### PR TITLE
Update and translate chapter 9 to spanish

### PR DESCRIPTION
**Pull request by ferllop**
I didn't dare to translate the word "pointed" in "the pointed functor" so I left it as "el functor pointed"

### CODE REVIEW

**Review by EstebanMarin — APPROVED** [review]
nice!!!

**Comment by EstebanMarin** [comment]
Thanks for all your hard work.

**Comment by ferllop** [comment]
You're welcome. It's a pleasure!
By the way.. it did not merge.. should I do something?

**Comment by EstebanMarin** [comment]
Though I did. Thanks!

**Pull request merged**
