### PR TITLE
fixed link to chapter 2

### PR DESCRIPTION
**Pull request by gabrielperales**

### CODE REVIEW

**Comment by EdgarOrtegaRamirez** [comment]
@gabrielperales good catch. :+1:

**Comment by gabrielperales** [comment]
I'm reading at this moment and I have seen a weird sentence on the chapter 2. At least in Spain we wouldn't say [*Si no puedes recuperar tu dinero, quizás puedas intercambiarlo por algo más incómodo*](https://github.com/MostlyAdequate/mostly-adequate-guide-es/blame/master/ch2-es.md#L186), I think we could say something like *Si no puedes recuperar tu dinero, quizás puedas cambiarlo por algo menos incómodo (o por algo que te moleste menos)*. Everything else is very good :-).

**Comment by VictorGa** [comment]
Good point. We already agreed on revising all chapters whenever they are finished checking if everything makes sense, since we are three people translating it at the moment.

We should do more of this checks indeed.

**Comment by guumaster** [comment]
:+1:

**Comment by gabrielperales** [comment]
Another little typo @guumaster [here](https://github.com/MostlyAdequate/mostly-adequate-guide-es/blame/master/ch3-es.md#L71) (nuestra ~~nuestro~~)

**Comment by guumaster** [comment]
Well, we need a complete review of all chapters. you can create a PR per chapter, or point the typos here and we'll fix them when we get to the review process. 

You are invited, of course :)

**Pull request merged**
